### ISSUE TITLE
Using with Reactive Forms

### ISSUE THREAD

**Issue by aalencar** [jkuri/ng2-datepicker#135]
I created a form and want to receive a string from the `ng2-datepicker` instead of the Object itself.
 
My approach was to use `[(ngModel)]="date"` and then extract just the date string from the `formatted` property, though doing this way I can't use `ngModel` inside an Angular 2 `formGroup`.

What is the best way to accomplish that using Reactive forms?

**Comment by jkuri** [comment]
hi @aalencar. not sure if best way but I would set some temporary variable and set `(ngModelChange)` on datepicker, then update variable that you are using accordingly.

**Comment by aalencar** [comment]
Hey @jkuri, I tried a simple approach.

Assigned `formControlName=date" and to extract the value I did:

`this.myModel.date = this.myForm.value.date.formatted`.

It seems to work fine.

Thank you.

**Comment by jkuri** [comment]
yw.

**Comment by kiruthika94** [comment]
Hi , I am facing the same issue with reactive forms.
<ng-datepicker  formControlName="date"[(ngModel)]="startDate" [options]="options"></ng-datepicker>
 i am getting error.
Uncaught Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'ng-datepicker'.
1. If 'ngModel' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("              <div id="datepicker">
                        <ng-datepicker  formControlName="date" [ERROR ->][(ngModel)]="startDate" [options]="options"></ng-datepicker>
                        <!--<input id=""): ng:///AppModule/AppComponent.html@234:63
No provider for NgControl ("
                      <td>
                        <div id="datepicker">
                        [ERROR ->]<ng-datepicker  formControlName="date" [(ngModel)]="startDate" [options]="options"></ng-datepicker>
"): ng:///AppModule/AppComponent.html@234:24
    at syntaxError (compiler.js:485)
    at TemplateParser.parse (compiler.js:24660)
    at JitCompiler._parseTemplate (compiler.js:34471)
    at JitCompiler._compileTemplate (compiler.js:34446)
    at eval (compiler.js:34347)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:34347)
    at eval (compiler.js:34217)
    at Object.then (compiler.js:474)
    at JitCompiler._compileModuleAndComponents (compiler.js:34216)
syntaxError @ compiler.js:485
TemplateParser.parse @ compiler.js:24660
JitCompiler._parseTemplate @ compiler.js:34471
JitCompiler._compileTemplate @ compiler.js:34446
(anonymous) @ compiler.js:34347
JitCompiler._compileComponents @ compiler.js:34347
(anonymous) @ compiler.js:34217
then @ compiler.js:474
JitCompiler._compileModuleAndComponents @ compiler.js:34216
JitCompiler.compileModuleAsync @ compiler.js:34110
CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:230
PlatformRef.bootstrapModule @ core.js:5568
(anonymous) @ main.ts:11
../../../../../src/main.ts @ main.bundle.js:96
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:111
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
