### ISSUE TITLE
Getting error "No SelectDirective specified" when trying to extend the Ionic datepicker

### ISSUE THREAD

**Issue by dcrosta** [jkuri/ng2-datepicker#91]
I am following the instructions at https://github.com/jkuri/ng2-datepicker/blob/flex/README.md (on branch "flex" which appears to be the most current) and getting "No SelectDirective specified" when I try to render the page. Here's what I have done:

1. My component:

```typescript
@Component(DatePickerIonicComponent.extendConfig({
  selector: 'form-datepicker',
  styleUrls: ['form-datepicker.component.scss'],
}, FormDatepickerComponent))
export class FormDatepickerComponent extends DatePickerIonicComponent {
  // there is literally nothing here yet
}
```

2. My template (for another component, which wants to use the `FormDatepickerComponent`:

```html
<form-datepicker singleSelect></form-datepicker>
```

3. The module which owns the `FormDatepickerComponent`:

```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { BrowserModule } from '@angular/platform-browser';

import { DatePickerModule, DatePickerIonicComponent, SingleSelectDirective } from 'ng2-datepicker';

import * as components from './components';
import * as layouts from './layouts';
import * as pipes from './pipes';
import * as services from './services';
import * as validators from './validators';

const all = imported => Object.keys(imported).map(k => imported[k]);

@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        BrowserModule,
        DatePickerModule,
    ],
    declarations: [
        ...all(components),
        ...all(layouts),
        ...all(pipes),
        ...all(validators),
    ],
    providers: [
        ...all(services),
    ],
    exports: [
        ...all(components),
        ...all(layouts),
        ...all(pipes),
        ...all(validators),
        DatePickerIonicComponent,
        SingleSelectDirective,
    ]
})
export class SharedModule { }
```

When I navigate to the page with the template as in step 2 above, I get this lovely error:

```
error_handler.js:47EXCEPTION: Uncaught (in promise): Error: Error in ./BasicInfoComponent class BasicInfoComponent - inline template:40:4 caused by: No SelectDirective specified. DatePicker must be coupled with a SelectDirective
Error: Error in ./BasicInfoComponent class BasicInfoComponent - inline template:40:4 caused by: No SelectDirective specified. DatePicker must be coupled with a SelectDirective
    at ViewWrappedError.BaseError [as constructor] (http://app.lvh.me:4200/main.bundle.js:6381:34)
    at ViewWrappedError.WrappedError [as constructor] (http://app.lvh.me:4200/main.bundle.js:6410:16)
    at new ViewWrappedError (http://app.lvh.me:4200/main.bundle.js:51352:16)
    at _View_BasicInfoComponent0.DebugAppView._rethrowWithContext (http://app.lvh.me:4200/main.bundle.js:73623:23)
    at _View_BasicInfoComponent0.DebugAppView.create (http://app.lvh.me:4200/main.bundle.js:73569:18)
    at _View_BasicInfoComponent_Host0.createInternal (BasicInfoComponent_Host.ngfactory.js:23:14)
    at _View_BasicInfoComponent_Host0.AppView.create (http://app.lvh.me:4200/main.bundle.js:73354:21)
    at _View_BasicInfoComponent_Host0.DebugAppView.create (http://app.lvh.me:4200/main.bundle.js:73566:44)
    at ComponentFactory.create (http://app.lvh.me:4200/main.bundle.js:51101:36)
    at ViewContainerRef_.createComponent (http://app.lvh.me:4200/main.bundle.js:51758:45)
```

I've tried moving the import and exports to other modules, all with the same error. If I use `<datepicker-ionic>` directly, of course, it works.

I have version 2.0.0-dev5 of the ng2-datepicker, version 2.0.2 of angular itself, and 1.0.0-beta.17 of angular-cli.

**Comment by ghetolay** [comment]
You must define a constructor as well. I've updated the readme (amongs other changes) but didn't push it yet.

```js
import { BaseSelect } from 'ng2-datepicker';

@Component(...)
                                                                       //next release
export class FormDatepickerComponent extends DatePickerIonicComponent /*DatePickerIonicComponent<any, BaseSelect<any>> */ {
    constructor(select: BaseSelect<any>) {
       super(select);
   }
}
```

If you know you'll always use that datepicker with singleSelect you can inject `SingleSelect` instead of `BaseSelect` but this will only make sense for the next release where datepicker classes are parameterized.

Great news from Angular 2 team, they'll implement component inheritance so we won't need to call `extendConfig()` nor have to redefine the constructor.

**Comment by dcrosta** [comment]
That constructor doesn't work (or rather, the `super()` call doesn't, since the base class constructor takes 4 parameters), so I've tried this, but I get the same error:

```typescript
@Component(DatePickerIonicComponent.extendConfig({
  selector: 'form-datepicker',
  styleUrls: ['form-datepicker.component.scss'],
}, FormDatepickerComponent))
export class FormDatepickerComponent extends DatePickerIonicComponent {

  constructor(renderer: Renderer, el: ElementRef, cd: ChangeDetectorRef, @Optional() select: BaseSelect<any>) {
    super(renderer, el, cd, select);
  }
}
```

(that's just copypasta from https://github.com/jkuri/ng2-datepicker/blob/flex/src/components/ionic/datepickerionic.ts)

**Comment by ghetolay** [comment]
You're right you must copy paste the exact same constructor (without any public/private).

Can you try with the last commit ? I've made changes since dev5 that may resolve this issue.
Problem is API change a little so you'll have to adapt your code and I'm not sure readme is up to date with code. I'm on gitter if you need help.

I'll try to release a dev6 this weekend.

**Comment by dcrosta** [comment]
Thanks for your help on gitter -- appreciate it.

**Comment by KlausNie** [comment]
I have the same problem, but only, if i want to extract my custom DatePicker into a separate module. 

"ng2-datepicker": "2.0.0-dev5"

module:
`
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {TranslateModule} from 'ng2-translate/ng2-translate';
import {FormsModule}   from '@angular/forms';
import {SelectModule} from 'ng2-select/ng2-select';
import {DatePickerModule} from 'ng2-datepicker';

import {CustomDatePickerComponent} from './custom-datepicker.component';

export {CustomDatePickerComponent}

@NgModule({
    imports: [FormsModule, SelectModule, TranslateModule, CommonModule, DatePickerModule],
    exports: [CustomDatePickerComponent],
    declarations: [CustomDatePickerComponent]
})

export class CustomDatePickerModule {}
`

component:
`
import { Component, ElementRef, Renderer, ChangeDetectorRef, Optional } from '@angular/core';
import { DatePickerIonicComponent, BaseSelect } from 'ng2-datepicker';

@Component(DatePickerIonicComponent.extendConfig({
    selector: 'hi-datepicker',
    styles: [require('./custom-datepicker.component.scss')]
}, CustomDatePickerComponent))
export class CustomDatePickerComponent extends DatePickerIonicComponent {

    constructor(renderer: Renderer, elRef: ElementRef, cd: ChangeDetectorRef, @Optional() select: BaseSelect<any>) {
        super(renderer, elRef, cd, select);
    }


    registerOnChange(fn: any) {
        //Return a js date instead of a moment date
        super.registerOnChange((momentDate: any) => fn(momentDate ? momentDate.toDate() : momentDate));
    }
}
`

As you can see, the constructor is just copypasted, still the same error. As said this only happens if i try to extract it into a separate module. Anyone a clue of why i get the error?

**Comment by ghetolay** [comment]
The v2 and it's corresponding branch (flex) have been discontinued. 
You should either use the stable v1 or try the new [repo](https://github.com/Imbasoft/ng-imbaDatepicker) which follows the v2 but still at an experimental stage.
